variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind

before_script:
  - docker info

ubuntu-test-job:
  stage: test
  image: ubuntu:latest
  script:
    - docker build os/pop
