name: Ubuntu Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --no-cache --progress=plain -f pop.Dockerfile . 2>&1 | tee build.log
    - name: Upload Build Log
      uses: actions/upload-artifact@v3.1.1
      with:
        path: build.log
        retention-days: 7
