alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias close='exit'
alias clr='clear'
alias apt-update='sudo apt update; apt list --upgradable'
alias apt-upgrade='sudo apt upgrade'
alias nala-update='sudo nala update; nala list --upgradable'
alias nala-upgrade='sudo nala upgrade'
alias settings='gnome-control-center'
alias extract='tar -xvzf'

alias list-apps='get_apt_packages && get_flatpak_packages && get_snap_packages'
